### ISSUE TITLE
SetPlayerName

### ISSUE THREAD

**Issue by audriuslio** [BlastHackNet/mod_s0beit_sa#11]
Hi,

It's possible to change player name to what i want with cheats? or maybe if it do not exist you could create that function or command?

**Comment by audriuslio** [comment]
How change name to null i mean empty like setplayername(playerid,"");

**Comment by audriuslio** [comment]
And too why i'am reconnecting when use this command?

**Comment by THE-FYP** [comment]
nickname cannot be shorter than 3 letters. and you can't change your nickname without rejoin.
