### ISSUE TITLE
Incoming Packets patches bugged

### ISSUE THREAD

**Issue by bourne9** [BlastHackNet/mod_s0beit_sa#13]
My games freezes after a second or two whenever I activate any patch from the incoming packets. I think it's bugged and needs a fix.

You can reproduce the problem. For example, activate Bullet Data patch and wait for someone to shoot in the streaming area of yours and your game will freeze.

**Comment by THE-FYP** [comment]
fixed in v4.4.1.1

**Comment by bourne9** [comment]
Wow, that fast ??? Thanks a bunch.

**Comment by THE-FYP** [comment]
my fault. forgot to add the installer.

**Comment by bourne9** [comment]
Ah, no biggies. Might as well add another bug. Sometimes, if I activate all RPCs via Toggle All, I get crashed, happens sometimes not all the times, specifically the first time, you might look into that too.
