### ISSUE TITLE
Receiving Bone Vec

### ISSUE THREAD

**Issue by S0PEX** [BlastHackNet/mod_s0beit_sa#14]
Hey,

i saw that pSAMP_Actor->pGTAEntity contains void pointers to aka Bones ?
Like : `pSAMP_Actor->pGTAEntity->pHead` is there also any struct out there ? I had a loot with reclass at it, but could find any vec3s there.

Do you know more ?

**Comment by THE-FYP** [comment]
your question has nothing to do with mod_sa. i can't definitely say if there is any structure that you are trying to find.
i'd recommend you asking this question in gta modding forums.
