### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by OverZHack** [BlastHackNet/mod_s0beit_sa#26]
Good, I want to know how to edit the mods menu (the one that appears in the game), Could you tell me which file to edit? I also need the program to edit it.

**Comment by OverZHack** [comment]
Friend, I have translated all the "mod_sa" (the configuration file), but I also want to translate the menu inside the game, Can you tell me how to access the edit of this? I think it is editing the d3d8.dll but not editing it .I will leave your credit intact ...

**Comment by THE-FYP** [comment]
File named `dumb_menu.cpp`.

**Comment by OverZHack** [comment]
To see, I was editing the mod "Over Light" but now I will translate this, is there any way to change the logo? (In OverLight you can ...)

**Comment by THE-FYP** [comment]
What logo? mod_sa has no any logo inside.

**Comment by OverZHack** [comment]
Oh.The Photo upload screen

**Comment by THE-FYP** [comment]
Do you mean the loading screen?

**Comment by OverZHack** [comment]
Yes

**Comment by THE-FYP** [comment]
It's not related to mod_sa in any way, it's from SA:MP (or GTA: SA in case of singleplayer).

**Comment by OverZHack** [comment]
Yes,when you enter a server your loading screen show credits to S0beit
