### ISSUE TITLE
It is possible?

### ISSUE THREAD

**Issue by ENeMy235** [BlastHackNet/mod_s0beit_sa#29]
Hello, it is possible to make a shortcut for toggle vehicle collision? And indicator for it.
And indicator for vehicle spin (key protection). It spins car, when it's on roof.

And freeze vehicle spin in air, it can have shortcut, but it's possible to make it functional only when you holding the key?

**Comment by THE-FYP** [comment]
all of these changes cannot be applied via config file, if you need these features you have to add such functionality to the source code.
