### ISSUE TITLE
Error : Gta has stoping working

### ISSUE THREAD

**Issue by alexpetrut93** [BlastHackNet/mod_s0beit_sa#33]
Hi !
When samp open gtasa - gtasa : Gta has stoping working
specs
Windows 10 64bit
I5 3230m
6gbram
Radeon 8750m

**Comment by THE-FYP** [comment]
make sure that your samp version is 0.3.7 R1

**Comment by alexpetrut93** [comment]
Yes it is.

**Comment by alexpetrut93** [comment]
Sorry it was r2. Why r2 give error ?

**Comment by THE-FYP** [comment]
mod_sa is incompatible with r2, you have to downgrade your samp client to r1 in order to use mod_sa.

**Comment by AGVD** [comment]
how to downgrade samp client ? to R1

**Comment by THE-FYP** [comment]
install 0.3.7 R1: http://files.sa-mp.com/sa-mp-0.3.7-install.exe
also you can install [this](https://blast.hk/threads/18815/) to have all features from 0.3.7 R2 in 0.3.7 R1.
