### ISSUE TITLE
[CRITICAL] MOD_SA

### ISSUE THREAD

**Issue by Xenirum-Core** [BlastHackNet/mod_s0beit_sa#34]
Проблема в том что тупо крашится самп, при сборке и запуске чита игра просто крашит, пробовал даже пребилженый из раздела Release ставить всё равно тот же эррор, я предпологаю что венец этого преступления это sampPatchDisableAnticheat(); т.к после его отключения игра запускается на на долю секунды при этом успевает отрисовывать интерфейс чита, я предполагаю что этот краш связан с обновление клиента до 0.3.7-R2 и может быть разработчики сампа накрутили там что-то с античитом.

Лог эррора
[error.log](https://github.com/BlastHackNet/mod_s0beit_sa/files/1610114/error.log)

**Comment by THE-FYP** [comment]
mod_sa несовместим с 0.3.7-R2, для работы требуется 0.3.7-R1.

**Comment by Xenirum-Core** [comment]
А исправлять данный недочёт в ваши планы входит ?

**Comment by THE-FYP** [comment]
это не недочёт. обновление на новую версию клиента требует немалых усилий, а весомых причин на это нет. более того, есть весомые причины не обновлять его - всем пользователям придётся обновлять не только клиент сампа, но и, в связи с этим, другие моды, которые зависят от версии, и многие из них тоже могут не поддерживать новую версию.
так что поддержки 0.3.7 R2 нет и не будет.

**Comment by Xenirum-Core** [comment]
Но проблема в том что r2 уже так сказать официальнле обновление и его уже можно скачать на оф сайте.
