### ISSUE TITLE
How i can downgrade samp r2 to r1 ?

### ISSUE THREAD

**Issue by AGVD** [BlastHackNet/mod_s0beit_sa#35]

**Comment by THE-FYP** [comment]
install 0.3.7 R1: http://files.sa-mp.com/sa-mp-0.3.7-install.exe
also you can install [this](https://blast.hk/threads/18815/) to have all features from 0.3.7 R2 in 0.3.7 R1.

**Comment by AGVD** [comment]
thanks..
