### ISSUE TITLE
Stick to nearest car

### ISSUE THREAD

**Issue by Jordy1212** [BlastHackNet/mod_s0beit_sa#44]
Hello, key_stick_nearest is being registered as TYPE_KEY but it should be TYPE_KEYCOMBO. This is breaking its functionality because cheat_handle_stick checks if a combination of keys is pressed.

Also want to thank you for keeping mod_sa up to date all these years.

**Comment by NarutoUA** [comment]
Hello, good catch.
It would be nice if you send us a pull request.

**Comment by Jordy1212** [comment]
Done

**Comment by Jordy1212** [comment]
Thanks for accepting my pull request. I will close this issue.
