### ISSUE TITLE
why no r2 version?

### ISSUE THREAD

**Issue by vaguiners** [BlastHackNet/mod_s0beit_sa#46]

**Comment by DopemanOG** [comment]
>this
I just saw SAMP was updated to R2 version and s0beit just crashes xd
Would it be possible for you to update s0beit as well? 
thanks in advance

**Comment by THE-FYP** [comment]
there is no reason to bother with it, 0.3.7 R2 has no significant changes.

**Comment by vaguiners** [comment]
u fking tard
