### ISSUE TITLE
Alt tabbing breaks everything.

### ISSUE THREAD

**Issue by avail** [BlastHackNet/mod_s0beit_sa#5]
I believe it only happens when there's a controller plugged in.
Alt tabbing disables every keyboard-related control (nothing from the SA UI responds, e.g escape or T for chat in SAMP)
Only way to fix it is to re-log, which gets annoying.

**Comment by bourne9** [comment]
Set your game resolution lower than your highest native resolution.

**Comment by THE-FYP** [comment]
closing this issue due to obsolescence. please let me know if your question is still actual.
