### ISSUE TITLE
0.3.7 R3 or R2, Please!

### ISSUE THREAD

**Issue by NemanjaMAX** [BlastHackNet/mod_s0beit_sa#51]
Most of the servers started BANNING SA:MP R1...
I know at least 3 servers with that blocking...
Please update or tell me what I need to change to make it work...

**Comment by Zayan-Imran** [comment]
It seems s0biet project has been deserted, in my opinion.

**Comment by NarutoUA** [comment]
Just download samp version changer. We won't update m0d_sa to 0.3.7-R3

**Comment by NemanjaMAX** [comment]
@NarutoUA link? I cannot find it...
