### ISSUE TITLE
DirectX9 inssue, when i use the cheat painel my character don´t move

### ISSUE THREAD

**Issue by RughCuttle** [BlastHackNet/mod_s0beit_sa#6]
When i start the GTA SA exe, he says "was not possible to locate the entry point Direct3DCreate9Ex procedure in the dynamic link library d3d9.dll" and when i press ok for 20 times it works, when i use the cheat painel the SAMP-Patches is not there and some feature provide craches of my GTA, and when i close the cheat painel my character don´t move no more.

**Comment by satoshifurude** [comment]
I have the almost the same Issue more like if you have Windows 8/8.1 or Win 10. That the Direct x9.0c some reason not really install at all. Enb Series looks bad(If you use Motion Blur) that you know i think. I have an problem if i put any d3d9.dll on Gta Sa Directory is just crashes if you use default samp but if i use samp debug crashes not. I use Windows 10 x64 Enterprise.

**Comment by THE-FYP** [comment]
closing this issue due to obsolescence. please let me know if your question is still actual.
